name: TicTacToe CI

# 1. Workflow-Trigger
on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 2. Code auschecken
      - uses: actions/checkout@v4

      # 3. JDK 11 installieren
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      # 4. Build & Tests
      - name: Build and run tests
        run: mvn clean test
        working-directory: ./tictactoe

      # 5. Nur auf main: JAR erzeugen
      - name: Package JAR
        if: github.ref == 'refs/heads/main'
        run: mvn clean package
        working-directory: ./tictactoe

      # 6. Nur auf main: JAR-Artefakt hochladen
      - name: Upload JAR artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: tictactoe-jar
          path: ./tictactoe/target/*.jar
